Foi adicionado o script de instalação da extensão do Chrome Remote De…
CMCuritiba/ETv4 pull request #101
Opened 2020-11-23 12:34 UTC by Felipe-T-Oliveira

**Descrição do Merge Request**

- O que há de novo?
  - Implementado o script que instala a extensao Chrome Remote Desktop
- O que mudou?
  - Script da 030-instala-programas.sh

Resolves: #100 

**Checklist**

- [ ] Eu rodei este código localmente
- [ ] Eu escrevi os testes necessários
- [ ] Eu utilizei _type-hints_ em meu código
- [ ] Eu não deixei dados _hard-coded_ em meu código
- [ ] Eu atualizei o CHANGELOG/README

**Considerações adicionais**

- Há mais alguma coisa que se deve saber?
O script também funciona para outras extensões, basta saber o nome de cada uma (google://extensions)

2020-11-23 13:41 UTC, brunosoli requested changes
Testei no Mint 20 Cinnamon, a extensão é instalada corretamente no Google Chrome mas o usuário pode excluí-la e, mesmo estando no `/opt/google/chrome/extensions`, ela não é reinstalada ao reiniciar o navegador.

**TODO**:

1. Verificar se não há uma policy para garantir que o usuário não possa remover a extensão; e
2. Habilitar extensão no FIrefox.

2020-11-23 15:07 UTC, Felipe-T-Oliveira commented
> Testei no Mint 20 Cinnamon, a extensão é instalada corretamente no Google Chrome mas o usuário pode excluí-la e, mesmo estando no `/opt/google/chrome/extensions`, ela não é reinstalada ao reiniciar o navegador.
> 
> **TODO**:
> 
>     1. Verificar se não há uma policy para garantir que o usuário não possa remover a extensão; e
> 
>     2. Habilitar extensão no FIrefox.

1- Ainda estou terminando de ler as polices, mas pelo que vi, bloquear pro user ta somente  no Win 8.1 pra frente.
2- O Chrome Remote Desktop é exclusivo do Chrome, pro firefox a saida seria achar outra extensão

2020-11-23 19:01 UTC, brunosoli commented
Além do plugin, também não tem um pacote a instalar?

Para o Firefox basta acessar o link e logar? Tem que adicionar o link para o Suporte nos favoritos gerenciados do Chrome e Firefox.

2020-11-24 11:43 UTC, Felipe-T-Oliveira commented
> Além do plugin, também não tem um pacote a instalar?
> 
> Para o Firefox basta acessar o link e logar? Tem que adicionar o link para o Suporte nos favoritos gerenciados do Chrome e Firefox.

Ate onde eu vi nao tem, somente o plugin, quando o usuario clica na extensao ja aparece o site pra ele logar com a conta google e talz. A extensão, Chrome Remote Desktop, so funciona pro navegador do Chrome, nao tem disponivel pro Firefox. Não sei se tem como colocar uma extensão nos favoritos, procurei ontem e vi que no maximo da pra fixar ela do lado da barra de pesquisa, mas isso so manualmente também

2020-11-24 11:47 UTC, brunosoli commented
Adicionar a URL nos favoritos, não a extensão.
Essa, se não me engano: https://remotedesktop.google.com/access

2020-11-25 15:06 UTC, Felipe-T-Oliveira commented
> Adicionar a URL nos favoritos, não a extensão.
> Essa, se não me engano: https://remotedesktop.google.com/access

Feito hehe Também ja testei na futura ETv5, funcionou também pleno.

2020-11-25 15:13 UTC, brunosoli commented
@Felipe-T-Oliveira, parece que você está se perdendo nos commits. Apareceu no diff que você está voltando configurações erradas que já havíamos corrigido. Não entendi também porque você adicionou uma pasta.

2020-11-26 12:49 UTC, Felipe-T-Oliveira commented
> @Felipe-T-Oliveira, parece que você está se perdendo nos commits. Apareceu no diff que você está voltando configurações erradas que já havíamos corrigido. Não entendi também porque você adicionou uma pasta.

Tinha pego os codigos da master em vez da develop, agora foram os codigos atuais e a pasta excluida 030 e 050 excluida.

2021-03-02 12:20 UTC, brunosoli commented
Sugiro não realizar este merge, visto que não utilizaremos mais o Google. Voltamos à prancheta para definir a melhor opção alternativa ao Google.
De acordo @diemello, @cpinheiro26, @ewerton-dif, @DePorto e @Felipe-T-Oliveira?

2021-03-02 12:36 UTC, ewerton-dif commented
Só para eu entender, esta extensão só funciona se tiver conta no gmail/google? Se não vamos mais usar o Google, então não dá para obrigar o usuário a ter conta, certo? E não é uma solução completa, pois não funciona no Firefox, que ainda é o browser padrão na CMC por causa do SPL... ou isto vai mudar? De qualquer forma, se precisarmos dar um suporte para o usuário em home-office, em seu computador pessoal, isto será feito usando um remote desktop em browser?

2021-03-02 12:45 UTC, Felipe-T-Oliveira commented
> Sugiro não realizar este merge, visto que não utilizaremos mais o Google. Voltamos à prancheta para definir a melhor opção alternativa ao Google.
> De acordo @diemello, @cpinheiro26, @ewerton-dif, @DePorto e @Felipe-T-Oliveira?

Por mim okay, dado que nao vao mais usar o Google, estou de acordo.

2021-03-02 12:51 UTC, brunosoli commented
> Só para eu entender, esta extensão só funciona se tiver conta no gmail/google? Se não vamos mais usar o Google, então não dá para obrigar o usuário a ter conta, certo? E não é uma solução completa, pois não funciona no Firefox, que ainda é o browser padrão na CMC por causa do SPL... ou isto vai mudar? De qualquer forma, se precisarmos dar um suporte para o usuário em home-office, em seu computador pessoal, isto será feito ? Se sim, penso que seria usando um remote desktop em browser, certo?

Essa issue nasceu da discussão de adotar uma ferramenta para permitir suporte remoto dentro e fora da cmc independente do dispositivo do usuário ser gerenciado ou não, conforme descrito [neste card](https://github.com/orgs/CMCuritiba/projects/6#card-42621781). Idealmente não deve ser necessária nenhuma conta senão a institucional.

2021-03-03 13:16 UTC, closed without merging