Hotfix87
CMCuritiba/ETv4 pull request #88
Opened 2020-09-14 13:38 UTC by lucaslm45

**Descrição do Merge Request**

- O que há de novo?
  - O grupo dif mudou para dtic

Resolves: #87 

**Checklist**

- [ x ] Eu rodei este código localmente
- [ x ] Eu escrevi os testes necessários
- [ ] Eu utilizei _type-hints_ em meu código
- [ ] Eu não deixei dados _hard-coded_ em meu código
- [ ] Eu atualizei o CHANGELOG/README

**Recursos adicionais**

Link para qualquer recurso externo utilizado (issue, projeto, website, etc)

**Considerações adicionais**

- Há mais alguma coisa que se deve saber?
- Alguma observação sobre o deployment?
- Alguma documentação adicional?

2020-09-14 14:00 UTC, brunosoli requested changes
Duas considerações:
- [ ] O script na pasta hotfixes está com espaço no nome;
- [ ] Os comandos `setfacl` podem estar dentro de um `if` (talvez o mesmo do sudoers?) para evitar que seja executado toda vez que o PC seja inicializado.

2020-09-14 17:08 UTC, brunosoli requested changes
@lucaslm45 e @diemello, o script 260 está correto mas estamos comendo bola neste hotfix.

Não é necessário dar o `setfacl` novamente porque o linux trata internamente o grupo pelo GID. Basta acessar qualquer estação de trabalho em produção e verificar que o grupo é resolvido corretamente para o novo nome:
```bash
getfacl /usr/bin/mate-terminal
```

No fim é preciso apenas o `sed` para o sudoers. Ainda assim me veio o seguinte, se houver qualquer palavra contendo 'dif' ela vai ser alterada, 'different', 'difficult', etc. Talvez seja melhor substituir o `sed` por:
```bash
sed -i 's/%dif/%dtic/g' /etc/sudoers
```

2020-09-14 21:18 UTC, lucaslm45 commented
Não sabia desse GID, vou remover o setfacl então.

Hmmmm, eu tinha cuidado com o grep pra buscar a palavra exata sem achar um 'different', mas não me atentei ao sed, vou ajustar.

2020-09-15 11:51 UTC, brunosoli approved these changes

2020-09-15 11:53 UTC, merged