Feature/up mint
CMCuritiba/ETv4 pull request #99
Opened 2020-11-16 15:03 UTC by lucaslm45

**Descrição do Merge Request**

- O que há de novo?
  - Foi mudado da versão Mate para Cinnamon.
- O que mudou?
  - O Mint 19.2 foi atualizado para o Mint 20 e removido a instalação do OwnCloud

Resolves: #54 
See also: #

**Checklist**

- [x] Eu rodei este código localmente
- [x] Eu escrevi os testes necessários
- [ ] Eu utilizei _type-hints_ em meu código
- [ ] Eu não deixei dados _hard-coded_ em meu código
- [x] Eu atualizei o CHANGELOG/README

**Considerações adicionais**

- Há mais alguma coisa que se deve saber?
Não foi possível configurar corretamente o Applet de temperatura nessa versão.

2021-06-28 17:32 UTC, Felipe-T-Oliveira approved these changes

2021-06-28 18:38 UTC, brunosoli commented on scripts/140-unattended-upgrades.sh
> +    echo "Source list do Chrome não encontrado, abortando."
Firefox ou Chrome?

2021-06-28 18:42 UTC, brunosoli requested changes
Precisa de muitas correções.

- Falta atualizar README com parametrização
- Melhorar nomes das variáveis no arquivo de parametrização
- Comando no script `root-terminal` precisa de revisão (vide policy)
- Bookmark no configura-taq deve ser gerenciado
- Realizar testes com sudo
- Realizar testes com terminal gráfico como usuário não privilegiado

2021-11-09 18:52 UTC, sandroizumi commented
Para configurar o nemo e tirar a opção de "Abrir no terminal", é só ir em _Editar_ -> _Preferências_ -> _Menus de contexto_ e desmarcar a opção. Acho que tem como colocar isso no skel para replicar em todos os usuários que forem criados.

2021-11-09 18:57 UTC, brunosoli commented
Possivelmente tem uma opção no gsettings pra isso. 

--
A Câmara Municipal de Curitiba, sob a LGPD 13.709/2018, tem o compromisso
de proteger toda informação coletada. Este e-mail e quaisquer anexos podem
conter informações privilegiadas ou confidenciais e destinadas ao uso
exclusivo do destinatário original, seu uso e reprodução dependem de
prévia autorização da Câmara Municipal de Curitiba. Se você recebeu
este e-mail por engano, por favor informe o remetente imediatamente e
exclua-o. A instituição não se responsabiliza pelo conteúdo expresso
nesta mensagem, sendo esta responsabilidade exclusiva do seu autor.
Não imprima este e-mail a menos que seja necessário. Se você se preocupa
com o meio ambiente como nós, evite imprimir e-mails.

2021-11-17 19:59 UTC, brunosoli requested changes
Correções indicadas.

2021-11-18 13:36 UTC, brunosoli commented
Com a remoção do _bifemorto_ tem que revisar o script `configsTaquigrafia/configuracao-taq.sh`.

2021-11-18 13:37 UTC, brunosoli approved these changes

2021-11-18 13:46 UTC, nicollasaque commented
> Com a remoção do _bifemorto_ tem que revisar o script `configsTaquigrafia/configuracao-taq.sh`.

Não sei porque, mas na verdade ele ainda ta instalando... vou ver isso

2021-11-18 14:23 UTC, nicollasaque commented
> > Com a remoção do _bifemorto_ tem que revisar o script `configsTaquigrafia/configuracao-taq.sh`.
> 
> Na verdaade ele já está vindo por padrão, desinstalo ele então?

não entendi muito bem o que fazer com o arquivo taqconfig

2021-11-23 12:45 UTC, sandroizumi commented on scripts/300-on-login.sh
> +    /usr/bin/chattr -f +i /home/*/Desktop/google-chrome.desktop
Só o do Firefox não, ele não está no diretório /usr/share/pixmaps/, como os outros

2021-11-23 14:05 UTC, nicollasaque commented on scripts/300-on-login.sh
> +    /usr/bin/chattr -f +i /home/*/Desktop/google-chrome.desktop
Ele não está sendo colocado mesmo, mas é só colocarmos, no projeto já tem a imagem do ícone do firefox, o que acha?

2021-11-23 14:17 UTC, sandroizumi commented on scripts/300-on-login.sh
> +    /usr/bin/chattr -f +i /home/*/Desktop/google-chrome.desktop
Vamos colocar, para que a parte visual da imagem fique perfeita para o usuário final. Desta parte, só falta isso, outros ícones e menu estão ok.

2021-11-23 14:31 UTC, nicollasaque reviewed
@sandroizumi acho que arrumei a questão do ícone do firefox com esse commit, você consegue confirmar?

2021-11-23 14:35 UTC, brunosoli commented on scripts/300-on-login.sh
> +    /usr/bin/chattr -f +i /home/*/Desktop/google-chrome.desktop
IMHO, vocês podem remover o ícone do firefox desse repo e simplesmente dar um `cp` do `/usr/share/applications/firefox.desktop` para o Desktop/skel. Resolve e simplifica, não?

2021-11-23 14:42 UTC, nicollasaque commented on scripts/300-on-login.sh
> +    /usr/bin/chattr -f +i /home/*/Desktop/google-chrome.desktop
Hum, resolvi de outra maneira, você acha que devemos fazer isso que falou da mesma forma?

2021-11-30 19:57 UTC, sandroizumi reviewed
@brunosoli Com essas últimas alterações, o arquivo nslc.conf não está gravando as informações de _uri_, _base_, _bindnd_ e _bindpw_. Acho que teremos que voltar o que era antes para gravar corretamente

2021-11-30 20:10 UTC, brunosoli commented
As URIs e bases de busca são configurados somente na instalação do `nslcd` e do `libnss-ldapd` via debconf. Mas o bind é configurado manualmente.
Nenhum está funcionando?

2021-12-03 19:11 UTC, brunosoli reviewed
Ainda falta testar bem:

1. Configurações do CUPS
2. Configurações no dconf

2021-12-03 19:17 UTC, brunosoli commented on scripts/120-ldap-install.sh
> +if ! grep -q "^employeeNumber" "$NSLCDCONF"; then
```suggestion
if ! grep -q "employeeNumber" "$NSLCDCONF"; then
```

2021-12-08 20:18 UTC, brunosoli commented
Configurações do CUPS validadas.

2021-12-09 17:50 UTC, brunosoli commented
Fazemos o merge para o develop e, após homologação pela equipe de @CMCuritiba/div-de-suporte a gente faz o PR para o main.
Beleza @sandroizumi ?

2021-12-09 17:59 UTC, sandroizumi commented
@brunosoli blz, configurações validadas

2021-12-09 18:00 UTC, merged

2022-01-12 18:57 UTC, tsocher commented
Detalhes durante o uso na nova imagem, para registro:

- DTIC  não está no sudores
- Não montou o Terminal na tela pra DTIC (deve ser o Pc com nome errado)
- Vinagre não instalado e acesso ao PC não funciona de outra estação
- Ownlcloud não instalado.